### ISSUE TITLE
Fruegel - Lift and Strike error with camera angle

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#92] opened 2024-05-30 21:51 UTC
**Describe the bug**
As soon as Fruegel smashes the body into the ground, the angle of the camera changes to beneath the ground. 

**To Reproduce**
Fight Fruegel for the first time. 

**Expected behavior**
He should smash us into the ground, but not that hard.. Camera angle should change, but not below the ground.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/76b460fb-cafe-4beb-b722-a9b5db9a1da1

**Comment by Wulves** [comment] 2024-07-22 16:30
Duplicate of #1285 which was fixed, can now be closed.

**Closed as completed** 2024-07-23 12:50 UTC
