### ISSUE TITLE
Beginning of Dart's explanation in the Shack - Text background fades to black

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains-Public-Test#89] opened 2024-05-30 19:18 UTC
**Describe the bug**
As the background fades to black and the text box remains on the screen, the background behind the text box fades to black.

**To Reproduce**
1. You'll want to have the chatter between everyone in the shack still available.  
2. There should be a save in SC before the Prairie.
3. Follow the story to the Shack.

**Expected behavior**
Background fading while textbox background remains the same.

![duckstation-qt-x64-ReleaseLTCG_dan947DF8L](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/a6a1ba75-99a8-4d69-8700-164098cd66c1)

![duckstation-qt-x64-ReleaseLTCG_3AWIe80DCZ](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170750797/bcbd98b3-45f6-4427-83bc-a050fd29e4fa)

**Comment by LordMonoxide** [comment] 2024-07-25 00:27
Closing as duplicate of #19

**Closed as completed by LordMonoxide** 2024-07-25 00:27 UTC
